import { useMemo, useState, type ReactNode } from 'react'

import { Math } from '../../components/Math'

import { BruhatDiagram } from './components/BruhatDiagram'
import { WiringDiagram } from './components/WiringDiagram'
import {
  bruhatGraph,
  bruhatLeq,
  descents,
  longestElement,
  numReducedWords,
  oneLine,
  reducedWord
} from './model'
import { generatorTex, reducedWordTex } from './tex'

const RANKS = [2, 3, 4] as const

const selectedBtn = 'h-9 w-9 rounded-md bg-indigo-600 font-medium text-white shadow-sm'
const plainBtn =
  'h-9 w-9 rounded-md border border-slate-200 bg-white transition hover:border-indigo-400 dark:border-slate-700 dark:bg-slate-900'

function factorial(k: number): number {
  let result = 1
  for (let i = 2; i <= k; i += 1) {
    result *= i
  }
  return result
}

export function CoxeterPage() {
  const [n, setN] = useState(3)
  const [selected, setSelected] = useState(factorial(3) - 1)

  const graph = useMemo(() => bruhatGraph(n), [n])
  const node = graph.nodes[selected]
  const below = useMemo(() => {
    const set = new Set<number>()
    graph.nodes.forEach((other, index) => {
      if (bruhatLeq(other.perm, node.perm)) {
        set.add(index)
      }
    })
    return set
  }, [graph, node])

  const word = reducedWord(node.perm)
  const rightDescents = descents(node.perm)
  const isLongest = oneLine(node.perm) === oneLine(longestElement(n))

  function chooseN(value: number): void {
    setN(value)
    // w_0 is last in lexicographic order; select it so the diagram opens full.
    setSelected(factorial(value) - 1)
  }

  return (
    <div className="py-6">
      <header className="mb-8">
        <h1 className="text-2xl font-bold tracking-tight">Coxeter Groups</h1>
        <p className="mt-2 max-w-2xl leading-relaxed text-slate-600 dark:text-slate-400">
          The symmetric group <Math tex="S_n" /> is the Coxeter group of type <Math tex="A_{n-1}" />
          : it is generated by the adjacent transpositions <Math tex="s_i" />, each swapping
          positions <Math tex="i" /> and <Math tex="i+1" />. A permutation&rsquo;s <em>length</em>{' '}
          <Math tex="\ell(w)" /> is its number of inversions, the fewest generators needed to build
          it. Ranked by length and ordered by the <em>Bruhat order</em>, the group becomes a graded
          poset - click any permutation to explore it.
        </p>
      </header>

      <section className="mb-4 flex flex-wrap items-center gap-2">
        <span className="text-sm font-medium text-slate-600 dark:text-slate-400">
          <Math tex="S_n" />, <Math tex="n" /> =
        </span>
        {RANKS.map((value) => (
          <button
            key={value}
            type="button"
            onClick={() => chooseN(value)}
            className={value === n ? selectedBtn : plainBtn}
          >
            {value}
          </button>
        ))}
        <span className="ml-auto text-sm text-slate-500">
          {graph.nodes.length} permutations &middot; longest length{' '}
          <Math tex={`\\ell(w_0) = ${graph.maxLength}`} />
        </span>
      </section>

      <div className="flex flex-col gap-8 lg:flex-row lg:items-start">
        <div className="w-full rounded-xl border border-slate-200 bg-white p-3 shadow-sm lg:min-w-0 lg:flex-1 dark:border-slate-800 dark:bg-slate-900">
          <BruhatDiagram
            graph={graph}
            size={680}
            selected={selected}
            below={below}
            onSelect={setSelected}
          />
        </div>

        <dl className="grid w-full grid-cols-[auto_1fr] gap-x-6 gap-y-3 text-sm lg:w-auto lg:min-w-60">
          <dt className="text-slate-500">Permutation</dt>
          <dd className="font-mono font-semibold">{oneLine(node.perm)}</dd>

          <dt className="text-slate-500">Length</dt>
          <dd className="font-medium">
            <Math tex={`\\ell(w) = ${node.length}`} />
          </dd>

          <dt className="text-slate-500">Right descents</dt>
          <dd className="font-medium">
            {rightDescents.length === 0 ? (
              <span className="text-slate-400">none</span>
            ) : (
              <Math tex={rightDescents.map((i) => generatorTex(i)).join(',\\; ')} />
            )}
          </dd>

          <dt className="text-slate-500">Reduced word</dt>
          <dd className="font-medium">
            <Math tex={reducedWordTex(word)} />
          </dd>

          <dt className="text-slate-500">Reduced words</dt>
          <dd className="font-medium">{numReducedWords(node.perm)}</dd>

          <dt className="text-slate-500">Below it</dt>
          <dd className="font-medium">
            {below.size} of {graph.nodes.length}
            {isLongest && (
              <span className="ml-2 rounded-full bg-indigo-100 px-2 py-0.5 text-[11px] font-semibold text-indigo-700 dark:bg-indigo-950/50 dark:text-indigo-300">
                <Math tex="w_0" />
              </span>
            )}
          </dd>

          <dt className="self-start text-slate-500">Wiring</dt>
          <dd>
            <WiringDiagram n={n} word={word} size={320} />
          </dd>
        </dl>
      </div>

      <div className="mt-10 grid gap-4 sm:grid-cols-2">
        <ConceptCard title="Length is inversions">
          Writing <Math tex="w" /> in one-line notation, <Math tex="\ell(w)" /> counts the pairs{' '}
          <Math tex="i < j" /> with <Math tex="w(i) > w(j)" />. Each adjacent transposition{' '}
          <Math tex="s_i" /> changes the length by exactly one, so a shortest word has exactly{' '}
          <Math tex="\ell(w)" /> letters.
        </ConceptCard>

        <ConceptCard title="Reduced words are braids">
          The wiring diagram draws a reduced word as crossing strands. Different reduced words for
          the same <Math tex="w" /> are related by the braid relations{' '}
          <Math tex="s_i s_{i+1} s_i = s_{i+1} s_i s_{i+1}" /> and <Math tex="s_i s_j = s_j s_i" />{' '}
          for <Math tex="|i - j| \ge 2" />.
        </ConceptCard>

        <ConceptCard title="The Bruhat order">
          <Math tex="u \le w" /> exactly when a reduced word for <Math tex="w" /> contains a reduced
          word for <Math tex="u" /> as a subword. The highlighted nodes are the interval{' '}
          <Math tex="[e, w]" />: every permutation below the one you picked.
        </ConceptCard>

        <ConceptCard title="Top and bottom">
          The identity <Math tex="e" /> is the unique minimum. The longest element{' '}
          <Math tex="w_0" /> reverses the word, has length <Math tex="\binom{n}{2}" />, and sits
          above everything - so its interval is the whole group.
        </ConceptCard>
      </div>
    </div>
  )
}

function ConceptCard({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
      <h3 className="font-semibold tracking-tight">{title}</h3>
      <p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-400">{children}</p>
    </section>
  )
}
